const crypto=require('crypto');
const COOKIE='juan_ws_session';
const allowedTables=new Set(['clients','projects','payments','project_items','deliverables']);
const tableColumns={clients:new Set(['id','client_number','name','email','phone','address','notes','created_at','updated_at']),projects:new Set(['id','project_number','client_id','client_name','client_email','client_phone','client_address','title','status','delivery_status','start_date','deadline_date','payment_due_date','total_amount','subtotal_amount','discount_amount','rush_fee','workload_rush_rate','workload_rush_fee','workload_at_booking','rush_days_early','rush_base_fee','rush_load_factor','rush_project_workload','system_maintenance_charge','project_type','priority','notes','deliverables','deadline_auto','invoice_number','invoice_issue_date','invoice_due_date','deleted','archived_at','created_at','updated_at']),payments:new Set(['id','project_id','amount_paid','payment_date','payment_method','reference_no','notes','created_at','updated_at']),project_items:new Set(['id','project_id','name','qty','price','type','addon_type','product_code','source_product_code','source_item_name','category','item_discount','sort_order','created_at','updated_at']),deliverables:new Set(['id','project_id','name','item_name','status','completed','progress','parent_id','is_group','source_type','order_item_id','order_item_occurrence','package_name','completed_at','sort_order','created_at','updated_at'])};
function b64(v){return Buffer.from(v).toString('base64url')}
function sign(v){const secret=String(process.env.SESSION_SECRET||'');if(secret.length<32)throw new Error('SESSION_SECRET is not configured securely');return crypto.createHmac('sha256',secret).update(v).digest('base64url')}
function makeSession(){const payload=b64(JSON.stringify({exp:Date.now()+12*60*60*1000,nonce:crypto.randomBytes(12).toString('hex')}));return `${payload}.${sign(payload)}`}
function validSession(req){const raw=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith(COOKIE+'='))?.slice(COOKIE.length+1);if(!raw)return false;const [p,s]=raw.split('.');if(!p||!s)return false;let expected;try{expected=Buffer.from(sign(p))}catch{return false}const actual=Buffer.from(s);if(expected.length!==actual.length||!crypto.timingSafeEqual(expected,actual))return false;try{return JSON.parse(Buffer.from(p,'base64url')).exp>Date.now()}catch{return false}}
function sameOrigin(req){const origin=req.headers.origin;if(!origin)return true;const host=req.headers.host;return origin===`https://${host}`||origin===`http://${host}`}
function headers(res){res.setHeader('Cache-Control','no-store');res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','DENY');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=()');}
function sanitizeObject(table,obj){const allowed=tableColumns[table];const out={};for(const [k,v] of Object.entries(obj||{})){if(!allowed.has(k))continue;if(typeof v==='string'&&v.length>10000)throw new Error('Input exceeds permitted size');out[k]=v;}return out}
function csrfFor(sessionCookie){const secret=String(process.env.CSRF_SECRET||'');if(secret.length<32)throw new Error('CSRF_SECRET is not configured securely');return crypto.createHmac('sha256',secret).update(sessionCookie).digest('base64url')}
module.exports={COOKIE,allowedTables,makeSession,validSession,sameOrigin,headers,sanitizeObject,csrfFor};
